### ISSUE TITLE
Modify gradle.properties os independent way

### ISSUE THREAD

**Issue by jvalkeal** [spring-io/spring-gradle-build-action#5]
Currently actions assume home path of `/home/runner` which is valid only on linux runner.

```
on:
  workflow_dispatch:
jobs:
  one:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Home
      shell: bash
      run: |
        echo "$HOME"
        ls $HOME
        mkdir -p $HOME/.gradle
        echo 'foo=bar' >> $HOME/.gradle/gradle.properties
        cat $HOME/.gradle/gradle.properties
```

Runner context don't have home but `bash` is supported on all runners so `$HOME` is available.

linux:
```
{
  "debug": "1",
  "os": "Linux",
  "arch": "X64",
  "name": "GitHub Actions 4",
  "tool_cache": "/opt/hostedtoolcache",
  "temp": "/home/runner/work/_temp",
  "workspace": "/home/runner/work/atest6"
}

HOME: /home/runner
```
mac:
```
{
  "debug": "1",
  "os": "macOS",
  "arch": "X64",
  "name": "GitHub Actions 3",
  "tool_cache": "/Users/runner/hostedtoolcache",
  "temp": "/Users/runner/work/_temp",
  "workspace": "/Users/runner/work/atest6"
}

HOME: /Users/runner
```
win:
```
{
    "debug": "1",
    "os": "Windows",
    "arch": "X64",
    "name": "GitHub Actions 2",
    "tool_cache": "C:\\hostedtoolcache\\windows",
    "temp": "D:\\a\\_temp",
    "workspace": "D:\\a\\atest6"
  }
  
HOME: /c/Users/runneradmin
```
